# Generated by Django 5.0.1 on 2024-01-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField()),
                ('rate', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Driver Profile',
                'db_table': 'driver_profile',
            },
        ),
        migrations.CreateModel(
            name='JounrneyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_destination', models.CharField(max_length=150)),
                ('end_destination', models.CharField(max_length=150)),
                ('km_travelled', models.IntegerField()),
                ('eta', models.IntegerField()),
                ('date', models.DateField()),
                ('cost', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Journey Info',
                'db_table': 'journey_info',
            },
        ),
    ]
