# Generated by Django 4.2.7 on 2024-01-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
