# Generated by Django 4.2.7 on 2024-01-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_driverprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverprofile',
            options={'verbose_name_plural': 'driver_profile'},
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
