# Generated by Django 4.2.7 on 2024-01-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_driverprofile_options_driverprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jounrneyinfo',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jounrneyinfo',
            name='end_destination',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jounrneyinfo',
            name='km_travelled',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jounrneyinfo',
            name='start_destination',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
