# Generated by Django 4.2.7 on 2024-03-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_jounrneyinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
