"""
Django settings for fee_my_ride_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import dj_database_url
from pathlib import Path
import os


from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'website/static/website/assets/js', 'serviceworker.js')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-szx0!l)jj+(b+13qno^z^^&rw)x0^%&_&&cqa(ect32#8s6w(i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'website.apps.WebsiteConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap4',
    'pwa',
    'django_extensions',
]


CRISPY_TEMPLATE_PACK = 'bootstrap4'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fee_my_ride_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fee_my_ride_project.wsgi.application'



PWA_APP_NAME = 'fee_my_ride'
PWA_APP_DESCRIPTION = "FeeMyRide PWA"
PWA_APP_THEME_COLOR = '#000000'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = 'login'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': 'media/app.png',
        'sizes': '512x512',
        'purpose': 'any'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': 'media/default.jpg',
        'sizes': '160x160',
        'purpose': 'any'
    }
]

PWA_APP_SCREENSHOTS = [
    {
        'src': 'media/app.png',
        'sizes': '512x512',
        'type': 'image/png',
        'label': 'homescreen'
    },
    {
        'src': 'media/screenshot.png',
        'sizes': '632x776',
        'type': 'image/png',
        'label': 'home'
    },


]
PWA_APP_SPLASH_SCREEN = [
    {
         'src': 'media/default.jpg',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#postgres://myriderate_django_user:hCpa0Fbv1Nj1o1AOMeIQ73DUYATzRjVE@dpg-cno020a0si5c73aul2k0-a.oregon-postgres.render.com/myriderate_django
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        #'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'sLATvkWJchSRcKhnboVLTLGXBKcfipVu',
        'HOST': 'roundhouse.proxy.rlwy.net',
        'PORT': '19247',
    }
}

#DATABASES["default"] = dj_database_url.parse("postgres://myriderate_django_user:hCpa0Fbv1Nj1o1AOMeIQ73DUYATzRjVE@dpg-cno020a0si5c73aul2k0-a.oregon-postgres.render.com/myriderate_django")
GDAL_LIBRARY_PATH = r'C:\OSGeo4W\bin\gdal307'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
LOGIN_URL = '/login/'
#LOGIN_REDIRECT_URL = reverse_lazy('home')
EMAIL_BACKEND  = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_BACKEND  = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_POST = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'michaeljchirwa@gmail.com'
EMAIL_HOST_PASSWORD = 'sowhuuqcxgafipje'
#EMAIL_FILE_PATH = BASE_DIR / 'emails'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
